;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        asm-comment
        base64-decode-region
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        comment-region
        downcase-region
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        emmet-expand-line
        eval-and-replace
        html-line
        indent-for-tab-command
        kill-region
        markdown-exdent-or-delete
        mouse-buffer-menu
        nxml-electric-slash
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-metaleft
        org-metaright
        org-return-indent
        org-self-insert-command
        org-yank
        paredit-backward-kill-word
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-newline
        paredit-open-round
        paredit-semicolon
        repeat
        shell-command
        write-file
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        comint-previous-input
        mouse-set-region
        previous-buffer
        set-fill-prefix
        ))
